checks:
  javascript: true
build:
  environment:
    mongodb: '3.2'
  tests:
    override:
      - eslint-run .eslintrc
      -
        command: 'npm test'
        coverage:
            file: 'coverage/clover.xml'
            format: 'clover'
filter:
  excluded_paths:
    - tests/*
