checks:
  javascript: true
build:
  environment:
    mongodb: '3.2'
  tests:
    override:
      -
        command: 'yarn test'
        coverage:
            file: 'coverage/clover.xml'
            format: 'clover'
      - 'yarn run lint'
filter:
  excluded_paths:
    - tests/*
