language: node_js
node_js: '12'
script:
  - npm test
  - npm run lint
services: mongodb
deploy:
  provider: npm
  email: developer@ridi.com
  api_key:
    secure: oFBBSl5ynrmuiy/ULqItLf6750ImbYYiD2m3L/HCuWN4gfI1cIeDlnUAeHF7vVPRD9Ya+hwgFwXFFyxnmicUsIVnANeMJ1gC2U08svyhwUmkgGMkzCxOldWeHzPepP9at+6vYQWoDxckde/t1qNC7Hz7QMJqu5jbygb+fv25EBhcaIaVDEILSOJUI4Qa1TllPsBQiujiryMVyfu/KWt3Hi4bYqFCn5uZ+QZFlMEGXPAU6LYIQqJ0Q2M/ie3vjElZuj0vWlpd3KpoOxv3AdkW3yrdThSlzQUVGMa7iCNpdegQwJPezipZ1Kb87nwN8Iwajybib7qJiewtDZ6mWtksOJSamaatITs5ZeqBAFuG6HLMJd1f5kGSAxUOvNyk36pWX1ZslmP0Ju4znUIfN7Qzu1rF9acn6ewj6KBvedcTxU/ojJLytafFuZ1aVxThLcdvDVz5CC7fck5ahNmiOND7s+JkHof7gpCJMtWpMTfhveKXe2rynAxjXJK7UQkdeHYrg6gLQpi22AkE/Zi72sMQmjuCj3GhS9CuS+3UJC4j2C4CGkb9iS/8WHNLDgqyEXhFrSTrcS1laG3tzIRTNbaJuCprGeASye0KFjNlP3uc58RBS+aEXQyr/cZSul+KEwaCrANHqG9B1qkGhk1kSX73uKcWkIZFT9Ookfg8c/PyPGw=
  on:
    tags: true
